export LANG=C.UTF-8
export CXX=/opt/rh/gcc-toolset-12/root/bin/g++
export CC=/opt/rh/gcc-toolset-12/root/bin/gcc
if [ -d /usr/lib/jvm/jre-17-openjdk ]; then
  export JAVA_HOME=/usr/lib/jvm/jre-17-openjdk
fi
export JMX_PROMETHEUS_JAVAAGENT_VERSION=0.20.0
export PRESTO_HOME=/opt/presto
export PRESTISSIMO_HOME=/opt/prestissimo
export BUILD_BASE_DIR=_build
export EXTRA_CMAKE_FLAGS="-DPRESTO_ENABLE_TESTING=ON -DPRESTO_ENABLE_PARQUET=ON -DPRESTO_ENABLE_S3=ON -DPRESTO_ENABLE_REMOTE_FUNCTIONS=ON -DPRESTO_ENABLE_JWT=ON -DPRESTO_STATS_REPORTER_TYPE=PROMETHEUS -DPRESTO_MEMORY_CHECKER_TYPE=LINUX_MEMORY_CHECKER -DPRESTO_ENABLE_SPATIAL=ON -DVELOX_BUILD_TESTING=OFF -DVELOX_ENABLE_SPARK=ON -DVELOX_ENABLE_SPARK_FUNCTIONS=ON"
export PATH=/root/bin:/root/.local/bin:$PATH
